services:
  influxdb:
    image: influxdb:2.0.4-alpine
    ports:
      - "8086:8086"
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.0.4-alpine
    entrypoint: influx setup --bucket coins -t test_token -o samonaco --username=samonaco --password=iamstrongpassword --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:1.18.1-alpine
    links: 
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment: 
      - TOKEN=test_token
      - TOKEN_LIST_URL=${TOKEN_LIST_URL}
    depends_on:
      - influxdb_cli
